

export const dummyCars =
    [
        {
            city_mpg: 23,
            class: 'compact car',
            combination_mpg: 24,
            cylinders: 4,
            displacement: 1.6,
            drive: 'fwd',
            fuel_type: 'gas',
            highway_mpg: 26,
            make: 'toyota',
            model: 'corolla',
            transmission: 'a',
            year: 1993
        },
        {
            city_mpg: 18,
            class: 'suv',
            combination_mpg: 20,
            cylinders: 6,
            displacement: 3.5,
            drive: 'awd',
            fuel_type: 'gas',
            highway_mpg: 23,
            make: 'honda',
            model: 'cr-v',
            transmission: 'a',
            year: 2015
        },
        {
            city_mpg: 30,
            class: 'sedan',
            combination_mpg: 32,
            cylinders: 4,
            displacement: 2.0,
            drive: 'fwd',
            fuel_type: 'hybrid',
            highway_mpg: 35,
            make: 'hyundai',
            model: 'elantra',
            transmission: 'cvt',
            year: 2020
        },
        {
            city_mpg: 16,
            class: 'pickup',
            combination_mpg: 18,
            cylinders: 8,
            displacement: 5.0,
            drive: '4wd',
            fuel_type: 'gas',
            highway_mpg: 21,
            make: 'ford',
            model: 'f-150',
            transmission: 'a',
            year: 2018
        },
        {
            city_mpg: 50,
            class: 'compact car',
            combination_mpg: 52,
            cylinders: 4,
            displacement: 1.8,
            drive: 'fwd',
            fuel_type: 'electric',
            highway_mpg: 55,
            make: 'tesla',
            model: 'model 3',
            transmission: 'a',
            year: 2022
        },
        {
            city_mpg: 20,
            class: 'luxury',
            combination_mpg: 22,
            cylinders: 6,
            displacement: 3.0,
            drive: 'awd',
            fuel_type: 'gas',
            highway_mpg: 25,
            make: 'bmw',
            model: '5 series',
            transmission: 'a',
            year: 2017
        },
        {
            city_mpg: 15,
            class: 'sports car',
            combination_mpg: 17,
            cylinders: 8,
            displacement: 4.5,
            drive: 'rwd',
            fuel_type: 'gas',
            highway_mpg: 20,
            make: 'chevrolet',
            model: 'corvette',
            transmission: 'm',
            year: 2016
        },
        {
            city_mpg: 35,
            class: 'hatchback',
            combination_mpg: 37,
            cylinders: 3,
            displacement: 1.2,
            drive: 'fwd',
            fuel_type: 'hybrid',
            highway_mpg: 40,
            make: 'ford',
            model: 'fiesta',
            transmission: 'a',
            year: 2019
        },
        {
            city_mpg: 22,
            class: 'minivan',
            combination_mpg: 24,
            cylinders: 6,
            displacement: 3.3,
            drive: 'fwd',
            fuel_type: 'gas',
            highway_mpg: 27,
            make: 'chrysler',
            model: 'pacifica',
            transmission: 'a',
            year: 2021
        },
        {
            city_mpg: 55,
            class: 'sedan',
            combination_mpg: 58,
            cylinders: 0,
            displacement: 0,
            drive: 'awd',
            fuel_type: 'electric',
            highway_mpg: 60,
            make: 'lucid',
            model: 'air',
            transmission: 'a',
            year: 2023
        },
        {
            city_mpg: 13,
            class: 'suv',
            combination_mpg: 15,
            cylinders: 8,
            displacement: 6.2,
            drive: '4wd',
            fuel_type: 'gas',
            highway_mpg: 18,
            make: 'cadillac',
            model: 'escalade',
            transmission: 'a',
            year: 2020
        },
        {
            city_mpg: 25,
            class: 'wagon',
            combination_mpg: 27,
            cylinders: 4,
            displacement: 2.5,
            drive: 'awd',
            fuel_type: 'diesel',
            highway_mpg: 30,
            make: 'subaru',
            model: 'outback',
            transmission: 'a',
            year: 2018
        }
    ];